name = "website"
main = "worker.mjs"
compatibility_date = "2026-05-09"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CONTENT"
id = "00954cc67610474790579f2d0d10ec4c"
